// Mock data shaped to match the schema. Realistic, dense, and consistent.

export const USERS = [
  { id: 1,  name: "Aisha Patel",     email: "aisha.patel@helpdesk.co",    role: "CSR",       initials: "AP", color: "oklch(0.55 0.18 270)" },
  { id: 2,  name: "Marcus Chen",     email: "marcus.chen@helpdesk.co",    role: "CSR",       initials: "MC", color: "oklch(0.60 0.18 30)"  },
  { id: 3,  name: "Sofia Reyes",     email: "sofia.reyes@helpdesk.co",    role: "CSR",       initials: "SR", color: "oklch(0.58 0.16 155)" },
  { id: 4,  name: "James Okonkwo",   email: "james.o@helpdesk.co",        role: "Bridge",    initials: "JO", color: "oklch(0.55 0.18 220)" },
  { id: 5,  name: "Priya Mehta",     email: "priya.m@helpdesk.co",        role: "Bridge",    initials: "PM", color: "oklch(0.58 0.16 290)" },
  { id: 6,  name: "Leo Kowalski",    email: "leo.k@helpdesk.co",          role: "Developer", initials: "LK", color: "oklch(0.55 0.18 200)" },
  { id: 7,  name: "Nina Tanaka",     email: "nina.t@helpdesk.co",         role: "Developer", initials: "NT", color: "oklch(0.55 0.18 320)" },
  { id: 8,  name: "Diego Alvarez",   email: "diego.a@helpdesk.co",        role: "QA",        initials: "DA", color: "oklch(0.55 0.18 100)" },
  { id: 9,  name: "Hana Suzuki",     email: "hana.s@helpdesk.co",         role: "QA",        initials: "HS", color: "oklch(0.55 0.18 350)" },
  { id: 10, name: "Olivia Brooks",   email: "olivia.b@helpdesk.co",       role: "Admin",     initials: "OB", color: "oklch(0.50 0.20 280)" },
];

// You — the current viewer's identity per role
export const ME = {
  Client:    { id: 101, name: "Elena Rivera",   initials: "ER", color: "oklch(0.55 0.18 50)",  role: "Client",   company: "Northwind Retail" },
  CSR:       USERS[0],
  Bridge:    USERS[3],
  Developer: USERS[5],
  QA:        USERS[7],
  Admin:     USERS[9],
};

export const COMPANIES = [
  { id: 1, name: "Northwind Retail",     email: "support@northwind.example",  vip: true,  contacts: 18, openTickets: 9 },
  { id: 2, name: "Helios Logistics",     email: "ops@helioslog.example",      vip: true,  contacts: 12, openTickets: 4 },
  { id: 3, name: "Verdant Labs",         email: "it@verdantlabs.example",     vip: false, contacts: 6,  openTickets: 2 },
  { id: 4, name: "Aurora Financial",     email: "service@aurorafin.example",  vip: true,  contacts: 24, openTickets: 7 },
  { id: 5, name: "Pinecrest Health",     email: "tech@pinecrest.example",     vip: false, contacts: 8,  openTickets: 3 },
  { id: 6, name: "Riverbend Studios",    email: "support@riverbend.example",  vip: false, contacts: 4,  openTickets: 1 },
  { id: 7, name: "Cobalt Manufacturing", email: "it@cobaltmfg.example",       vip: true,  contacts: 15, openTickets: 5 },
];

export const CONTACTS = [
  { id: 11, name: "Elena Rivera",     email: "elena.rivera@northwind.example",   companyId: 1, primary: true,  initials: "ER" },
  { id: 12, name: "Tomás Hernández",  email: "t.hernandez@northwind.example",    companyId: 1, primary: false, initials: "TH" },
  { id: 13, name: "Yuki Watanabe",    email: "y.watanabe@helioslog.example",     companyId: 2, primary: true,  initials: "YW" },
  { id: 14, name: "Sven Hjelm",       email: "s.hjelm@verdantlabs.example",      companyId: 3, primary: true,  initials: "SH" },
  { id: 15, name: "Maya Greenfield",  email: "m.greenfield@aurorafin.example",   companyId: 4, primary: true,  initials: "MG" },
  { id: 16, name: "Devon Clarke",     email: "d.clarke@pinecrest.example",       companyId: 5, primary: true,  initials: "DC" },
  { id: 17, name: "Aaron Park",       email: "a.park@riverbend.example",         companyId: 6, primary: true,  initials: "AP" },
  { id: 18, name: "Greta Bauer",      email: "g.bauer@cobaltmfg.example",        companyId: 7, primary: true,  initials: "GB" },
];

export const STATUSES = {
  New:                  { name: "New",                   short: "New",       color: "var(--status-new)" },
  Open:                 { name: "Open",                  short: "Open",      color: "var(--status-open)" },
  WaitingClient:        { name: "Waiting for Client",    short: "Waiting",   color: "var(--status-waiting)" },
  Resolved:             { name: "Resolved",              short: "Resolved",  color: "var(--status-resolved)" },
  EscalatedDev:         { name: "Escalated to Dev",      short: "Escalated", color: "var(--status-escalated)" },
  UnderReview:          { name: "Under Review",          short: "Reviewing", color: "var(--status-review)" },
  DeferredSprint:       { name: "Deferred to Sprint",    short: "In Sprint", color: "var(--status-sprint)" },
  InDevelopment:        { name: "In Development",        short: "In Dev",    color: "var(--status-dev)" },
  InQA:                 { name: "In QA / Testing",       short: "In QA",     color: "var(--status-qa)" },
  ReadyDeploy:          { name: "Ready for Deployment",  short: "Ready",     color: "var(--status-deploy)" },
  Deployed:             { name: "Deployed",              short: "Deployed",  color: "var(--status-deployed)" },
  Closed:               { name: "Closed",                short: "Closed",    color: "var(--status-closed)" },
  Reopened:             { name: "Reopened",              short: "Reopened",  color: "var(--status-reopened)" },
};

export const PRIORITIES = {
  Critical: { name: "Critical", responseMin: 60,   resolutionMin: 240,   cls: "critical" },
  High:     { name: "High",     responseMin: 240,  resolutionMin: 480,   cls: "high" },
  Medium:   { name: "Medium",   responseMin: 480,  resolutionMin: 1440,  cls: "medium" },
  Low:      { name: "Low",      responseMin: 960,  resolutionMin: 3360,  cls: "low" },
};

export const CATEGORIES = ["Bug Report", "Feature Request", "Service Request", "Complaint", "General Inquiry", "Other"];
export const CHANNELS = ["Email", "Web Form", "Phone", "WhatsApp", "Walk-in"];

export const TAGS = [
  { id: 1, name: "billing" }, { id: 2, name: "checkout" }, { id: 3, name: "auth" },
  { id: 4, name: "mobile-ios" }, { id: 5, name: "mobile-android" }, { id: 6, name: "reports" },
  { id: 7, name: "api" }, { id: 8, name: "performance" }, { id: 9, name: "data-import" },
  { id: 10, name: "outage" }, { id: 11, name: "csv-export" }, { id: 12, name: "sso" },
];

// Helper: minutes-ago timestamps so SLAs feel live
const m = (mins) => new Date(Date.now() - mins * 60 * 1000);

export const TICKETS = [
  {
    id: 1001,
    ticket_id: "SUP-2026-0514-018",
    title: "Checkout fails with 502 after PayPal redirect on iOS Safari",
    description: "Customers are reporting a hard failure when returning from PayPal. The page hangs for 30s then shows our generic 502. Reproduced on iOS 17.4 Safari, fine on Chrome. Started ~2h ago. ~40 carts abandoned.",
    status: "Open",
    priority: "Critical",
    category: "Bug Report",
    channel: "Email",
    company: "Northwind Retail",
    contact: "Elena Rivera",
    contactEmail: "elena.rivera@northwind.example",
    csrId: 1,
    bridgeId: null,
    devId: null,
    qaId: null,
    raisedByCsr: false,
    tags: ["checkout", "outage", "mobile-ios"],
    createdMinAgo: 78,
    firstResponseMin: 22,
    slaResponse: { target: 60,  elapsed: 78, paused: false, breached: true,  met: true  },
    slaResolution: { target: 240, elapsed: 78, paused: false, breached: false, met: false },
    commentCount: 6,
    attachmentCount: 2,
    watchers: 4,
    reopens: 0,
    vip: true,
    new: false,
  },
  {
    id: 1002,
    ticket_id: "SUP-2026-0514-017",
    title: "CSV export of monthly orders cut off at row 10,000",
    description: "Finance team needs full month of orders. The 'Export Orders' button silently truncates at 10k rows. Workaround: filter by week. Blocking month-end close on Friday.",
    status: "EscalatedDev",
    priority: "High",
    category: "Bug Report",
    channel: "Web Form",
    company: "Aurora Financial",
    contact: "Maya Greenfield",
    contactEmail: "m.greenfield@aurorafin.example",
    csrId: 2,
    bridgeId: 4,
    devId: null,
    qaId: null,
    raisedByCsr: false,
    tags: ["csv-export", "reports"],
    createdMinAgo: 380,
    firstResponseMin: 35,
    slaResponse: { target: 240, elapsed: 380, paused: false, breached: false, met: true },
    slaResolution: { target: 480, elapsed: 380, paused: false, breached: false, met: false },
    commentCount: 9,
    attachmentCount: 4,
    watchers: 6,
    reopens: 0,
    vip: true,
    new: false,
  },
  {
    id: 1003,
    ticket_id: "SUP-2026-0514-016",
    title: "SSO login loop on the customer portal — Okta",
    description: "Users get bounced between Okta and our portal indefinitely. Cleared cookies fixes it temporarily. Likely state/cookie mismatch.",
    status: "InDevelopment",
    priority: "High",
    category: "Bug Report",
    channel: "Email",
    company: "Cobalt Manufacturing",
    contact: "Greta Bauer",
    contactEmail: "g.bauer@cobaltmfg.example",
    csrId: 1,
    bridgeId: 4,
    devId: 6,
    qaId: null,
    raisedByCsr: false,
    tags: ["sso", "auth"],
    createdMinAgo: 740,
    firstResponseMin: 40,
    slaResponse: { target: 240, elapsed: 740, paused: false, breached: false, met: true },
    slaResolution: { target: 480, elapsed: 740, paused: false, breached: true, met: false },
    commentCount: 12,
    attachmentCount: 1,
    watchers: 5,
    reopens: 0,
    vip: true,
    new: false,
  },
  {
    id: 1004,
    ticket_id: "SUP-2026-0514-015",
    title: "Need bulk-edit on product tags — feature request",
    description: "Tagging 400 products one by one is painful. Can we get a bulk tag editor with CSV upload? Happy to draft requirements.",
    status: "DeferredSprint",
    priority: "Medium",
    category: "Feature Request",
    channel: "Email",
    company: "Northwind Retail",
    contact: "Tomás Hernández",
    contactEmail: "t.hernandez@northwind.example",
    csrId: 1,
    bridgeId: 5,
    devId: 7,
    qaId: null,
    raisedByCsr: false,
    tags: ["data-import"],
    sprint: "Sprint 32",
    sprintDate: "Jun 02",
    createdMinAgo: 2880,
    firstResponseMin: 220,
    slaResponse: { target: 480, elapsed: 2880, paused: true, breached: false, met: true },
    slaResolution: { target: 1440, elapsed: 2880, paused: true, breached: false, met: false },
    commentCount: 7,
    attachmentCount: 0,
    watchers: 3,
    reopens: 0,
    vip: true,
    new: false,
  },
  {
    id: 1005,
    ticket_id: "SUP-2026-0514-014",
    title: "Invoice PDFs missing line-item discounts",
    description: "Last 3 invoices show discount column blank but amounts are deducted from totals — confusing for clients. Need fix before Friday batch run.",
    status: "WaitingClient",
    priority: "High",
    category: "Bug Report",
    channel: "Phone",
    company: "Helios Logistics",
    contact: "Yuki Watanabe",
    contactEmail: "y.watanabe@helioslog.example",
    csrId: 3,
    bridgeId: null,
    devId: null,
    qaId: null,
    raisedByCsr: true,
    tags: ["billing"],
    createdMinAgo: 240,
    firstResponseMin: 12,
    slaResponse: { target: 240, elapsed: 240, paused: true, breached: false, met: true },
    slaResolution: { target: 480, elapsed: 240, paused: true, breached: false, met: false },
    commentCount: 5,
    attachmentCount: 3,
    watchers: 2,
    reopens: 0,
    vip: true,
    new: false,
  },
  {
    id: 1006,
    ticket_id: "SUP-2026-0514-013",
    title: "Mobile app crashes on cold start (Android 14)",
    description: "Reproducible on Pixel 7 and Samsung S23 — opens to splash then crashes. Logcat attached.",
    status: "InQA",
    priority: "Critical",
    category: "Bug Report",
    channel: "WhatsApp",
    company: "Helios Logistics",
    contact: "Yuki Watanabe",
    contactEmail: "y.watanabe@helioslog.example",
    csrId: 2,
    bridgeId: 4,
    devId: 7,
    qaId: 8,
    raisedByCsr: true,
    tags: ["mobile-android"],
    createdMinAgo: 1140,
    firstResponseMin: 18,
    slaResponse: { target: 60, elapsed: 1140, paused: false, breached: false, met: true },
    slaResolution: { target: 240, elapsed: 1140, paused: false, breached: true, met: false },
    commentCount: 18,
    attachmentCount: 7,
    watchers: 8,
    reopens: 1,
    vip: true,
    new: false,
  },
  {
    id: 1007,
    ticket_id: "SUP-2026-0514-012",
    title: "Where do I download last quarter's usage report?",
    description: "Looking for the Q1 detailed usage report — I see Q4 in my downloads but not Q1.",
    status: "Resolved",
    priority: "Low",
    category: "General Inquiry",
    channel: "Email",
    company: "Verdant Labs",
    contact: "Sven Hjelm",
    contactEmail: "s.hjelm@verdantlabs.example",
    csrId: 3,
    bridgeId: null,
    devId: null,
    qaId: null,
    raisedByCsr: false,
    tags: ["reports"],
    createdMinAgo: 320,
    firstResponseMin: 9,
    resolvedMinAgo: 110,
    slaResponse: { target: 960, elapsed: 9,   paused: false, breached: false, met: true },
    slaResolution: { target: 3360, elapsed: 210, paused: false, breached: false, met: true },
    commentCount: 3,
    attachmentCount: 0,
    watchers: 1,
    reopens: 0,
    vip: false,
    new: false,
  },
  {
    id: 1008,
    ticket_id: "SUP-2026-0514-011",
    title: "API rate limit hits at 60 rpm — docs say 120",
    description: "We're being throttled at 60 requests per minute on /v2/orders but docs say plan limit is 120rpm. Logs attached.",
    status: "Open",
    priority: "Medium",
    category: "Bug Report",
    channel: "Email",
    company: "Riverbend Studios",
    contact: "Aaron Park",
    contactEmail: "a.park@riverbend.example",
    csrId: 1,
    bridgeId: null,
    devId: null,
    qaId: null,
    raisedByCsr: false,
    tags: ["api", "performance"],
    createdMinAgo: 90,
    firstResponseMin: 14,
    slaResponse: { target: 480, elapsed: 90, paused: false, breached: false, met: true },
    slaResolution: { target: 1440, elapsed: 90, paused: false, breached: false, met: false },
    commentCount: 2,
    attachmentCount: 1,
    watchers: 2,
    reopens: 0,
    vip: false,
    new: false,
  },
  {
    id: 1009,
    ticket_id: "SUP-2026-0514-010",
    title: "Add filter for 'last touched by me' to ticket list",
    description: "Would be huge for daily triage — show me only tickets I commented on or assigned myself to. Nice-to-have, not blocking.",
    status: "New",
    priority: "Low",
    category: "Feature Request",
    channel: "Web Form",
    company: "Pinecrest Health",
    contact: "Devon Clarke",
    contactEmail: "d.clarke@pinecrest.example",
    csrId: null,
    bridgeId: null,
    devId: null,
    qaId: null,
    raisedByCsr: false,
    tags: [],
    createdMinAgo: 14,
    slaResponse: { target: 960, elapsed: 14, paused: false, breached: false, met: false },
    slaResolution: { target: 3360, elapsed: 14, paused: false, breached: false, met: false },
    commentCount: 0,
    attachmentCount: 0,
    watchers: 0,
    reopens: 0,
    vip: false,
    new: true,
  },
  {
    id: 1010,
    ticket_id: "SUP-2026-0514-009",
    title: "Two-factor codes arriving 5+ minutes late",
    description: "SMS 2FA codes are arriving late — frequently after they expire. Email codes are fine. Started Tuesday.",
    status: "Open",
    priority: "High",
    category: "Bug Report",
    channel: "Phone",
    company: "Aurora Financial",
    contact: "Maya Greenfield",
    contactEmail: "m.greenfield@aurorafin.example",
    csrId: 2,
    bridgeId: null,
    devId: null,
    qaId: null,
    raisedByCsr: true,
    tags: ["auth"],
    createdMinAgo: 180,
    firstResponseMin: 28,
    slaResponse: { target: 240, elapsed: 180, paused: false, breached: false, met: true },
    slaResolution: { target: 480, elapsed: 180, paused: false, breached: false, met: false },
    commentCount: 4,
    attachmentCount: 0,
    watchers: 3,
    reopens: 0,
    vip: true,
    new: false,
  },
  {
    id: 1011,
    ticket_id: "SUP-2026-0514-008",
    title: "Deployed: line-discount fix on invoice PDFs",
    description: "Backport of #SUP-2026-0510-022. Discounts now render in the per-line column.",
    status: "Deployed",
    priority: "High",
    category: "Bug Report",
    channel: "Email",
    company: "Cobalt Manufacturing",
    contact: "Greta Bauer",
    contactEmail: "g.bauer@cobaltmfg.example",
    csrId: 1,
    bridgeId: 4,
    devId: 6,
    qaId: 9,
    raisedByCsr: false,
    tags: ["billing"],
    createdMinAgo: 4320,
    firstResponseMin: 20,
    resolvedMinAgo: 200,
    deployedMinAgo: 60,
    slaResponse: { target: 240, elapsed: 20, paused: false, breached: false, met: true },
    slaResolution: { target: 480, elapsed: 480, paused: false, breached: false, met: true },
    commentCount: 14,
    attachmentCount: 3,
    watchers: 5,
    reopens: 0,
    vip: true,
    new: false,
  },
  {
    id: 1012,
    ticket_id: "SUP-2026-0514-007",
    title: "Reopened: search returns no results for 'gateway'",
    description: "Same as #SUP-2026-0512-003 — search broke again after Tuesday's deploy.",
    status: "Reopened",
    priority: "Medium",
    category: "Bug Report",
    channel: "Web Form",
    company: "Pinecrest Health",
    contact: "Devon Clarke",
    contactEmail: "d.clarke@pinecrest.example",
    csrId: 3,
    bridgeId: null,
    devId: null,
    qaId: null,
    raisedByCsr: false,
    tags: ["api"],
    createdMinAgo: 45,
    slaResponse: { target: 480, elapsed: 45, paused: false, breached: false, met: false },
    slaResolution: { target: 1440, elapsed: 45, paused: false, breached: false, met: false },
    commentCount: 1,
    attachmentCount: 0,
    watchers: 2,
    reopens: 1,
    vip: false,
    new: false,
  },
];

// Detailed comment thread for the centerpiece ticket (1001)
export const COMMENTS_1001 = [
  {
    id: 1, type: "System", channel: "Internal",
    authorName: "STMS", authorRole: "System",
    minAgo: 78,
    body: "Ticket created via Email from elena.rivera@northwind.example. Priority Critical auto-set from VIP + 'outage' tag. SLA timer started.",
  },
  {
    id: 2, type: "Client_Facing", channel: "Email",
    authorId: 101, authorName: "Elena Rivera", authorRole: "Client",
    minAgo: 78, direction: "in",
    body: "Hi team — we're seeing customers fail at checkout after returning from PayPal. The page hangs ~30s then shows a 502. Reproduced on iOS Safari (17.4). About 40 abandoned carts in the last hour and it's accelerating.\n\nAttached: HAR file + 3 screenshots from affected customer sessions.",
    attachments: [
      { name: "checkout-failure.har", size: "1.4 MB" },
      { name: "screenshot-1.png", size: "284 KB" },
      { name: "screenshot-2.png", size: "302 KB" },
    ],
  },
  {
    id: 3, type: "Internal_Note", channel: "Internal",
    authorId: 1, authorName: "Aisha Patel", authorRole: "CSR",
    minAgo: 56,
    body: "Confirmed reproduction on iPad Safari. Chrome desktop is fine. Looking at gateway logs — seeing a spike in 502s from /checkout/return starting at 14:02. Pinging @James — this might already be on the dev side.",
  },
  {
    id: 4, type: "Client_Facing", channel: "Email",
    authorId: 1, authorName: "Aisha Patel", authorRole: "CSR",
    minAgo: 56,
    body: "Hi Elena — I've reproduced this and we're investigating now. As a temporary workaround, customers can complete checkout via the 'Card' option instead of PayPal while we look into it. I'll update you within 30 minutes.\n\n— Aisha (Support)",
  },
  {
    id: 5, type: "Internal_Note", channel: "Internal",
    authorId: 4, authorName: "James Okonkwo", authorRole: "Bridge",
    minAgo: 34,
    body: "Looked at the gateway. PayPal IPN listener is timing out — looks related to today's TLS cert rotation. Leo is on it. Calling this Tier-2 now so we can move fast.",
  },
  {
    id: 6, type: "System", channel: "Internal",
    authorName: "STMS", authorRole: "System",
    minAgo: 22,
    body: "Status changed: Open → Escalated to Dev by James Okonkwo. Bridge Person assigned: James Okonkwo. Developer assigned: Leo Kowalski.",
  },
];

// Activity / status history
export const ACTIVITY_1001 = [
  { kind: "create", minAgo: 78, text: "Ticket created via Email", actor: "Elena Rivera" },
  { kind: "assign", minAgo: 78, text: "Auto-assigned to Aisha Patel (CSR, round-robin)" },
  { kind: "status", minAgo: 70, text: "Status: New → Open", actor: "Aisha Patel" },
  { kind: "reply",  minAgo: 56, text: "First client-facing reply sent", actor: "Aisha Patel" },
  { kind: "sla",    minAgo: 45, text: "SLA: First Response met (35 min, target 60 min)" },
  { kind: "watcher",minAgo: 36, text: "James Okonkwo added as watcher" },
  { kind: "status", minAgo: 22, text: "Status: Open → Escalated to Dev", actor: "James Okonkwo" },
  { kind: "assign", minAgo: 22, text: "Developer assigned: Leo Kowalski", actor: "James Okonkwo" },
];

// Sprints
export const SPRINTS = [
  { id: 1, name: "Sprint 31", start: "May 05", end: "May 18", status: "Active",   tickets: 8, points: 34, completed: 22 },
  { id: 2, name: "Sprint 32", start: "May 19", end: "Jun 01", status: "Planned",  tickets: 6, points: 28, completed: 0 },
  { id: 3, name: "Sprint 33", start: "Jun 02", end: "Jun 15", status: "Planned",  tickets: 3, points: 14, completed: 0 },
  { id: 4, name: "Sprint 30", start: "Apr 21", end: "May 04", status: "Completed",tickets: 9, points: 40, completed: 40 },
];

// KB articles
export const KB_ARTICLES = [
  { id: 1, title: "Resetting two-factor authentication for a client", cat: "Auth & SSO",  status: "Published", views: 1284, updated: "2d ago", author: "Aisha Patel", linkedTickets: 14, tags: ["auth", "2fa"] },
  { id: 2, title: "Reproducing the PayPal IPN timeout — checklist",   cat: "Checkout",    status: "Published", views: 312,  updated: "4h ago", author: "James Okonkwo", linkedTickets: 6, tags: ["checkout", "gateway"] },
  { id: 3, title: "How to export full month of orders (workaround)",  cat: "Reports",     status: "Published", views: 892,  updated: "1w ago", author: "Marcus Chen", linkedTickets: 9, tags: ["csv-export", "reports"] },
  { id: 4, title: "Mobile app crash signatures — known causes",        cat: "Mobile",      status: "Published", views: 564,  updated: "3d ago", author: "Nina Tanaka", linkedTickets: 12, tags: ["mobile-android", "mobile-ios"] },
  { id: 5, title: "Triggering a manual SLA recalculation",            cat: "Operations",  status: "Draft",     views: 0,    updated: "1h ago", author: "Olivia Brooks", linkedTickets: 0, tags: ["sla"] },
  { id: 6, title: "Migrating a tenant from US-East to EU-West",       cat: "Migrations",  status: "Published", views: 145,  updated: "2w ago", author: "Priya Mehta", linkedTickets: 3, tags: ["infrastructure"] },
];

// Analytics — weekly numbers
export const ANALYTICS = {
  ticketsThisWeek: 184,
  ticketsLastWeek: 167,
  fcrRate: 84,         // first contact resolution %
  slaCompliance: 96.2,
  csat: 4.62,
  csatResponses: 73,
  csatRate: 41,        // response rate %
  avgResolutionHours: 6.8,
  openByPriority: { Critical: 3, High: 12, Medium: 34, Low: 22 },
  byChannel: [
    { name: "Email", value: 92 },
    { name: "Web Form", value: 41 },
    { name: "Phone", value: 28 },
    { name: "WhatsApp", value: 14 },
    { name: "Walk-in", value: 9 },
  ],
  daily: [22, 31, 28, 35, 24, 29, 15], // Mon-Sun
  resolved:[18, 26, 30, 32, 28, 30, 14],
  trendLabels: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
  csrLeaderboard: [
    { name: "Aisha Patel",   handled: 48, fcr: 91, csat: 4.8, slaHits: 47 },
    { name: "Marcus Chen",   handled: 41, fcr: 86, csat: 4.6, slaHits: 39 },
    { name: "Sofia Reyes",   handled: 39, fcr: 82, csat: 4.5, slaHits: 38 },
  ],
};

export const DATA = {
  USERS, ME, COMPANIES, CONTACTS, STATUSES, PRIORITIES,
  CATEGORIES, CHANNELS, TAGS, TICKETS,
  COMMENTS_1001, ACTIVITY_1001, SPRINTS, KB_ARTICLES, ANALYTICS,
};
